---
# tasks file for hephyvienna.workernode
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Install packages
  package:
    name: "{{ workernode_ui_pkgs if workernode_ui else workernode_wn_pkgs }}"
    state: present

- name: Install WLCG repo
  include_tasks: repo-wlcg.yml
  when: workernode_enable_repo_wlcg

- name: Install HEP_OSlibs
  package:
    name: "{{ workernode_hepos_pkgs }}"
    state: present

- name: Configure grid wn/ui for bash
  template:
    src: gridenv.sh.j2
    dest: /etc/profile.d/gridenv.sh

- name: Configure grid wn/ui for csh
  template:
    src: gridenv.csh.j2
    dest: /etc/profile.d/gridenv.csh

- name: Install HTCondor CE client
  block:

    - name: Install HTCondor repo
      include_tasks: repo-htcondor.yml

    - name: Install HTCondor CE Client packages
      package:
        name: htcondor-ce-client
        state: present

  when: workernode_install_htc_ce_client
