---
# tasks file for hephyvienna.grid-worker
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Install packages
  package:
    name: "{{ grid_worker_ui_pkgs if grid_worker_ui else grid_worker_wn_pkgs }}"
    state: present

- name: Install WLCG repo
  include_tasks: repo-wlcg.yml
  when: grid_worker_enable_repo_wlcg

- name: Install HEP_OSlibs
  package:
    name: "{{ grid_worker_hepos_pkgs }}"
    state: present

- name: Configure grid wn/ui for bash
  template:
    src: gridenv.sh.j2
    dest: /etc/profile.d/gridenv.sh

- name: Configure grid wn/ui for csh
  template:
    src: gridenv.csh.j2
    dest: /etc/profile.d/gridenv.csh

- block: Install HTCondor CE client

  - name: Install Condor repo
    include_tasks: repo-condor.yml

  - name: Install HTCondor CE Client
    package:
      name: htcondor-ce-client
      state: present

  when: grid_worker_install_htc_ce_client
