---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Enable EPEL
      package:
        name: epel-release
        state: present
        
  roles:
    - role: hephyvienna.grid
      vars:
        grid_vos:
          - cms
          - alice
          - belle
        grid_umd_repo_exclude:
          - dpm-*
          - lfc-*
          - lcgdm-*
    - role: hephyvienna.workernode
